# Generated by Django 5.2.7 on 2026-01-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker_app', '0004_alter_expense_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
